// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using P05Shop.API.Models;

#nullable disable

namespace P05Shop.API.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20231106004814_ReleaseDateRequired")]
    partial class ReleaseDateRequired
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("P06Shop.Shared.Shop.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(5000)
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Pages")
                        .HasColumnType("int");

                    b.Property<DateTime>("ReleaseDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design",
                            Pages = 830,
                            ReleaseDate = new DateTime(2023, 5, 12, 12, 0, 21, 967, DateTimeKind.Local).AddTicks(1964),
                            Title = "Gorgeous Wooden Chair"
                        },
                        new
                        {
                            Id = 2,
                            Description = "New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart",
                            Pages = 96,
                            ReleaseDate = new DateTime(2023, 7, 1, 9, 2, 26, 930, DateTimeKind.Local).AddTicks(9402),
                            Title = "Intelligent Cotton Towels"
                        },
                        new
                        {
                            Id = 3,
                            Description = "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients",
                            Pages = 712,
                            ReleaseDate = new DateTime(2023, 3, 20, 7, 8, 13, 876, DateTimeKind.Local).AddTicks(6272),
                            Title = "Generic Wooden Fish"
                        },
                        new
                        {
                            Id = 4,
                            Description = "The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive",
                            Pages = 675,
                            ReleaseDate = new DateTime(2022, 12, 20, 18, 52, 29, 922, DateTimeKind.Local).AddTicks(8517),
                            Title = "Handcrafted Steel Shoes"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support",
                            Pages = 699,
                            ReleaseDate = new DateTime(2023, 4, 17, 14, 16, 40, 992, DateTimeKind.Local).AddTicks(6567),
                            Title = "Ergonomic Plastic Car"
                        },
                        new
                        {
                            Id = 6,
                            Description = "The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive",
                            Pages = 839,
                            ReleaseDate = new DateTime(2023, 9, 30, 3, 46, 47, 512, DateTimeKind.Local).AddTicks(7860),
                            Title = "Fantastic Rubber Salad"
                        },
                        new
                        {
                            Id = 7,
                            Description = "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit",
                            Pages = 176,
                            ReleaseDate = new DateTime(2023, 2, 10, 13, 21, 18, 336, DateTimeKind.Local).AddTicks(556),
                            Title = "Handmade Granite Table"
                        },
                        new
                        {
                            Id = 8,
                            Description = "Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support",
                            Pages = 703,
                            ReleaseDate = new DateTime(2023, 5, 5, 9, 55, 4, 930, DateTimeKind.Local).AddTicks(3072),
                            Title = "Ergonomic Steel Pants"
                        },
                        new
                        {
                            Id = 9,
                            Description = "The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design",
                            Pages = 198,
                            ReleaseDate = new DateTime(2023, 1, 18, 22, 40, 30, 785, DateTimeKind.Local).AddTicks(9981),
                            Title = "Small Plastic Table"
                        },
                        new
                        {
                            Id = 10,
                            Description = "The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive",
                            Pages = 276,
                            ReleaseDate = new DateTime(2023, 5, 7, 0, 41, 4, 739, DateTimeKind.Local).AddTicks(2866),
                            Title = "Handmade Wooden Table"
                        },
                        new
                        {
                            Id = 11,
                            Description = "Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals",
                            Pages = 415,
                            ReleaseDate = new DateTime(2023, 5, 11, 5, 21, 16, 685, DateTimeKind.Local).AddTicks(2070),
                            Title = "Fantastic Concrete Chicken"
                        },
                        new
                        {
                            Id = 12,
                            Description = "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit",
                            Pages = 160,
                            ReleaseDate = new DateTime(2023, 8, 20, 10, 54, 1, 145, DateTimeKind.Local).AddTicks(1574),
                            Title = "Practical Granite Ball"
                        },
                        new
                        {
                            Id = 13,
                            Description = "Boston's most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles",
                            Pages = 74,
                            ReleaseDate = new DateTime(2023, 3, 22, 12, 51, 45, 101, DateTimeKind.Local).AddTicks(5005),
                            Title = "Intelligent Steel Salad"
                        },
                        new
                        {
                            Id = 14,
                            Description = "The Football Is Good For Training And Recreational Purposes",
                            Pages = 987,
                            ReleaseDate = new DateTime(2023, 6, 22, 2, 31, 18, 132, DateTimeKind.Local).AddTicks(568),
                            Title = "Sleek Steel Tuna"
                        },
                        new
                        {
                            Id = 15,
                            Description = "The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive",
                            Pages = 360,
                            ReleaseDate = new DateTime(2023, 2, 20, 12, 12, 12, 874, DateTimeKind.Local).AddTicks(7895),
                            Title = "Ergonomic Steel Shirt"
                        },
                        new
                        {
                            Id = 16,
                            Description = "Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals",
                            Pages = 246,
                            ReleaseDate = new DateTime(2022, 11, 9, 17, 27, 0, 59, DateTimeKind.Local).AddTicks(4644),
                            Title = "Handcrafted Rubber Bike"
                        },
                        new
                        {
                            Id = 17,
                            Description = "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients",
                            Pages = 643,
                            ReleaseDate = new DateTime(2023, 8, 18, 2, 40, 4, 622, DateTimeKind.Local).AddTicks(9231),
                            Title = "Small Steel Tuna"
                        },
                        new
                        {
                            Id = 18,
                            Description = "New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016",
                            Pages = 181,
                            ReleaseDate = new DateTime(2023, 9, 3, 23, 59, 45, 984, DateTimeKind.Local).AddTicks(5317),
                            Title = "Gorgeous Cotton Keyboard"
                        },
                        new
                        {
                            Id = 19,
                            Description = "New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart",
                            Pages = 627,
                            ReleaseDate = new DateTime(2023, 8, 2, 21, 50, 45, 543, DateTimeKind.Local).AddTicks(4756),
                            Title = "Unbranded Steel Car"
                        },
                        new
                        {
                            Id = 20,
                            Description = "The slim & simple Maple Gaming Keyboard from Dev Byte comes with a sleek body and 7- Color RGB LED Back-lighting for smart functionality",
                            Pages = 887,
                            ReleaseDate = new DateTime(2023, 6, 7, 19, 29, 57, 224, DateTimeKind.Local).AddTicks(8677),
                            Title = "Refined Fresh Mouse"
                        },
                        new
                        {
                            Id = 21,
                            Description = "The Football Is Good For Training And Recreational Purposes",
                            Pages = 939,
                            ReleaseDate = new DateTime(2023, 4, 4, 23, 11, 58, 394, DateTimeKind.Local).AddTicks(5473),
                            Title = "Ergonomic Plastic Computer"
                        },
                        new
                        {
                            Id = 22,
                            Description = "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients",
                            Pages = 705,
                            ReleaseDate = new DateTime(2023, 11, 4, 18, 20, 18, 872, DateTimeKind.Local).AddTicks(5703),
                            Title = "Tasty Plastic Cheese"
                        },
                        new
                        {
                            Id = 23,
                            Description = "The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design",
                            Pages = 331,
                            ReleaseDate = new DateTime(2023, 4, 11, 0, 20, 44, 817, DateTimeKind.Local).AddTicks(2853),
                            Title = "Tasty Metal Pants"
                        },
                        new
                        {
                            Id = 24,
                            Description = "New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016",
                            Pages = 224,
                            ReleaseDate = new DateTime(2023, 6, 28, 14, 26, 26, 82, DateTimeKind.Local).AddTicks(7869),
                            Title = "Intelligent Fresh Bacon"
                        },
                        new
                        {
                            Id = 25,
                            Description = "Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals",
                            Pages = 42,
                            ReleaseDate = new DateTime(2023, 6, 10, 7, 37, 34, 972, DateTimeKind.Local).AddTicks(4672),
                            Title = "Handcrafted Fresh Sausages"
                        },
                        new
                        {
                            Id = 26,
                            Description = "New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016",
                            Pages = 781,
                            ReleaseDate = new DateTime(2023, 7, 11, 12, 2, 19, 103, DateTimeKind.Local).AddTicks(7047),
                            Title = "Licensed Metal Mouse"
                        },
                        new
                        {
                            Id = 27,
                            Description = "The Football Is Good For Training And Recreational Purposes",
                            Pages = 249,
                            ReleaseDate = new DateTime(2022, 12, 18, 6, 25, 41, 539, DateTimeKind.Local).AddTicks(5457),
                            Title = "Ergonomic Metal Shoes"
                        },
                        new
                        {
                            Id = 28,
                            Description = "Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support",
                            Pages = 813,
                            ReleaseDate = new DateTime(2022, 11, 19, 16, 30, 56, 931, DateTimeKind.Local).AddTicks(9300),
                            Title = "Fantastic Frozen Gloves"
                        },
                        new
                        {
                            Id = 29,
                            Description = "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit",
                            Pages = 107,
                            ReleaseDate = new DateTime(2023, 10, 29, 22, 47, 28, 872, DateTimeKind.Local).AddTicks(6522),
                            Title = "Unbranded Granite Hat"
                        },
                        new
                        {
                            Id = 30,
                            Description = "New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart",
                            Pages = 906,
                            ReleaseDate = new DateTime(2023, 10, 9, 22, 7, 51, 0, DateTimeKind.Local).AddTicks(8222),
                            Title = "Generic Fresh Computer"
                        },
                        new
                        {
                            Id = 31,
                            Description = "The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design",
                            Pages = 125,
                            ReleaseDate = new DateTime(2022, 11, 13, 9, 54, 7, 739, DateTimeKind.Local).AddTicks(4916),
                            Title = "Generic Steel Ball"
                        },
                        new
                        {
                            Id = 32,
                            Description = "Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support",
                            Pages = 312,
                            ReleaseDate = new DateTime(2023, 3, 15, 0, 5, 30, 5, DateTimeKind.Local).AddTicks(1292),
                            Title = "Licensed Soft Salad"
                        },
                        new
                        {
                            Id = 33,
                            Description = "Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals",
                            Pages = 843,
                            ReleaseDate = new DateTime(2023, 8, 8, 15, 21, 55, 142, DateTimeKind.Local).AddTicks(5662),
                            Title = "Ergonomic Metal Soap"
                        },
                        new
                        {
                            Id = 34,
                            Description = "Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals",
                            Pages = 75,
                            ReleaseDate = new DateTime(2023, 4, 11, 1, 22, 58, 106, DateTimeKind.Local).AddTicks(1045),
                            Title = "Ergonomic Rubber Car"
                        },
                        new
                        {
                            Id = 35,
                            Description = "The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive",
                            Pages = 625,
                            ReleaseDate = new DateTime(2022, 11, 29, 17, 51, 20, 935, DateTimeKind.Local).AddTicks(3917),
                            Title = "Unbranded Wooden Soap"
                        },
                        new
                        {
                            Id = 36,
                            Description = "The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design",
                            Pages = 929,
                            ReleaseDate = new DateTime(2023, 8, 16, 19, 53, 51, 916, DateTimeKind.Local).AddTicks(4504),
                            Title = "Intelligent Plastic Cheese"
                        },
                        new
                        {
                            Id = 37,
                            Description = "The slim & simple Maple Gaming Keyboard from Dev Byte comes with a sleek body and 7- Color RGB LED Back-lighting for smart functionality",
                            Pages = 233,
                            ReleaseDate = new DateTime(2023, 10, 22, 16, 31, 28, 718, DateTimeKind.Local).AddTicks(6268),
                            Title = "Generic Steel Pizza"
                        },
                        new
                        {
                            Id = 38,
                            Description = "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients",
                            Pages = 530,
                            ReleaseDate = new DateTime(2023, 5, 19, 2, 37, 12, 198, DateTimeKind.Local).AddTicks(6077),
                            Title = "Ergonomic Fresh Keyboard"
                        },
                        new
                        {
                            Id = 39,
                            Description = "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients",
                            Pages = 707,
                            ReleaseDate = new DateTime(2023, 7, 17, 1, 7, 20, 836, DateTimeKind.Local).AddTicks(621),
                            Title = "Fantastic Metal Chair"
                        },
                        new
                        {
                            Id = 40,
                            Description = "Boston's most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles",
                            Pages = 472,
                            ReleaseDate = new DateTime(2022, 11, 20, 17, 10, 26, 168, DateTimeKind.Local).AddTicks(7316),
                            Title = "Small Metal Sausages"
                        },
                        new
                        {
                            Id = 41,
                            Description = "Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals",
                            Pages = 826,
                            ReleaseDate = new DateTime(2022, 11, 12, 8, 35, 34, 688, DateTimeKind.Local).AddTicks(3611),
                            Title = "Fantastic Metal Keyboard"
                        },
                        new
                        {
                            Id = 42,
                            Description = "The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design",
                            Pages = 306,
                            ReleaseDate = new DateTime(2023, 1, 10, 14, 19, 59, 323, DateTimeKind.Local).AddTicks(7105),
                            Title = "Refined Metal Fish"
                        },
                        new
                        {
                            Id = 43,
                            Description = "Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support",
                            Pages = 902,
                            ReleaseDate = new DateTime(2023, 8, 11, 23, 50, 56, 180, DateTimeKind.Local).AddTicks(9299),
                            Title = "Fantastic Soft Pants"
                        },
                        new
                        {
                            Id = 44,
                            Description = "The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive",
                            Pages = 764,
                            ReleaseDate = new DateTime(2022, 11, 18, 16, 40, 21, 248, DateTimeKind.Local).AddTicks(5121),
                            Title = "Practical Steel Tuna"
                        },
                        new
                        {
                            Id = 45,
                            Description = "The Nagasaki Lander is the trademarked name of several series of Nagasaki sport bikes, that started with the 1984 ABC800J",
                            Pages = 378,
                            ReleaseDate = new DateTime(2023, 8, 1, 7, 25, 52, 353, DateTimeKind.Local).AddTicks(4359),
                            Title = "Unbranded Cotton Soap"
                        },
                        new
                        {
                            Id = 46,
                            Description = "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients",
                            Pages = 956,
                            ReleaseDate = new DateTime(2023, 4, 9, 23, 42, 41, 811, DateTimeKind.Local).AddTicks(5887),
                            Title = "Gorgeous Frozen Towels"
                        },
                        new
                        {
                            Id = 47,
                            Description = "New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016",
                            Pages = 993,
                            ReleaseDate = new DateTime(2023, 1, 6, 0, 1, 45, 678, DateTimeKind.Local).AddTicks(5745),
                            Title = "Unbranded Wooden Chair"
                        },
                        new
                        {
                            Id = 48,
                            Description = "New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016",
                            Pages = 462,
                            ReleaseDate = new DateTime(2022, 11, 18, 23, 20, 40, 820, DateTimeKind.Local).AddTicks(3328),
                            Title = "Handmade Steel Pants"
                        },
                        new
                        {
                            Id = 49,
                            Description = "Boston's most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles",
                            Pages = 267,
                            ReleaseDate = new DateTime(2023, 6, 1, 21, 39, 45, 10, DateTimeKind.Local).AddTicks(2939),
                            Title = "Tasty Steel Cheese"
                        },
                        new
                        {
                            Id = 50,
                            Description = "New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016",
                            Pages = 16,
                            ReleaseDate = new DateTime(2023, 5, 24, 22, 41, 31, 553, DateTimeKind.Local).AddTicks(5037),
                            Title = "Incredible Concrete Salad"
                        });
                });

            modelBuilder.Entity("P06Shop.Shared.Shop.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Barcode")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(8,2)");

                    b.Property<DateTime>("ReleaseDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Barcode = "3",
                            Description = "The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design",
                            Price = 712.021981759007m,
                            ReleaseDate = new DateTime(2023, 3, 20, 7, 8, 13, 868, DateTimeKind.Local).AddTicks(8319),
                            Title = "Gorgeous Wooden Chair"
                        },
                        new
                        {
                            Id = 2,
                            Barcode = "7",
                            Description = "The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive",
                            Price = 839.010165513032m,
                            ReleaseDate = new DateTime(2023, 9, 30, 3, 46, 47, 505, DateTimeKind.Local).AddTicks(1182),
                            Title = "Handcrafted Steel Shoes"
                        },
                        new
                        {
                            Id = 3,
                            Barcode = "1",
                            Description = "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit",
                            Price = 198.083692779804m,
                            ReleaseDate = new DateTime(2023, 1, 18, 22, 40, 30, 778, DateTimeKind.Local).AddTicks(3268),
                            Title = "Handmade Granite Table"
                        },
                        new
                        {
                            Id = 4,
                            Barcode = "1",
                            Description = "The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive",
                            Price = 160.643399712929m,
                            ReleaseDate = new DateTime(2023, 8, 20, 10, 54, 1, 137, DateTimeKind.Local).AddTicks(4939),
                            Title = "Handmade Wooden Table"
                        },
                        new
                        {
                            Id = 5,
                            Barcode = "0",
                            Description = "Boston's most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles",
                            Price = 359.887736376788m,
                            ReleaseDate = new DateTime(2023, 2, 20, 12, 12, 12, 867, DateTimeKind.Local).AddTicks(1179),
                            Title = "Intelligent Steel Salad"
                        },
                        new
                        {
                            Id = 6,
                            Barcode = "8",
                            Description = "Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals",
                            Price = 181.360829243139m,
                            ReleaseDate = new DateTime(2023, 9, 3, 23, 59, 45, 976, DateTimeKind.Local).AddTicks(8609),
                            Title = "Handcrafted Rubber Bike"
                        },
                        new
                        {
                            Id = 7,
                            Barcode = "1",
                            Description = "New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart",
                            Price = 938.297015022625m,
                            ReleaseDate = new DateTime(2023, 4, 4, 23, 11, 58, 386, DateTimeKind.Local).AddTicks(8709),
                            Title = "Unbranded Steel Car"
                        },
                        new
                        {
                            Id = 8,
                            Barcode = "3",
                            Description = "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients",
                            Price = 223.882037785315m,
                            ReleaseDate = new DateTime(2023, 6, 28, 14, 26, 26, 75, DateTimeKind.Local).AddTicks(974),
                            Title = "Tasty Plastic Cheese"
                        },
                        new
                        {
                            Id = 9,
                            Barcode = "0",
                            Description = "Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals",
                            Price = 249.172251003875m,
                            ReleaseDate = new DateTime(2022, 12, 18, 6, 25, 41, 531, DateTimeKind.Local).AddTicks(8479),
                            Title = "Handcrafted Fresh Sausages"
                        },
                        new
                        {
                            Id = 10,
                            Barcode = "1",
                            Description = "Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support",
                            Price = 905.322284099796m,
                            ReleaseDate = new DateTime(2023, 10, 9, 22, 7, 50, 993, DateTimeKind.Local).AddTicks(1169),
                            Title = "Fantastic Frozen Gloves"
                        },
                        new
                        {
                            Id = 11,
                            Barcode = "3",
                            Description = "The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design",
                            Price = 842.480734222792m,
                            ReleaseDate = new DateTime(2023, 8, 8, 15, 21, 55, 134, DateTimeKind.Local).AddTicks(8364),
                            Title = "Generic Steel Ball"
                        },
                        new
                        {
                            Id = 12,
                            Barcode = "1",
                            Description = "Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals",
                            Price = 928.928430071533m,
                            ReleaseDate = new DateTime(2023, 8, 16, 19, 53, 51, 908, DateTimeKind.Local).AddTicks(7104),
                            Title = "Ergonomic Rubber Car"
                        },
                        new
                        {
                            Id = 13,
                            Barcode = "6",
                            Description = "The slim & simple Maple Gaming Keyboard from Dev Byte comes with a sleek body and 7- Color RGB LED Back-lighting for smart functionality",
                            Price = 706.948686653259m,
                            ReleaseDate = new DateTime(2023, 7, 17, 1, 7, 20, 828, DateTimeKind.Local).AddTicks(3193),
                            Title = "Generic Steel Pizza"
                        },
                        new
                        {
                            Id = 14,
                            Barcode = "3",
                            Description = "Boston's most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles",
                            Price = 306.262494314584m,
                            ReleaseDate = new DateTime(2023, 1, 10, 14, 19, 59, 315, DateTimeKind.Local).AddTicks(9549),
                            Title = "Small Metal Sausages"
                        },
                        new
                        {
                            Id = 15,
                            Barcode = "2",
                            Description = "Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support",
                            Price = 378.222576259273m,
                            ReleaseDate = new DateTime(2023, 8, 1, 7, 25, 52, 345, DateTimeKind.Local).AddTicks(6732),
                            Title = "Fantastic Soft Pants"
                        },
                        new
                        {
                            Id = 16,
                            Barcode = "6",
                            Description = "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients",
                            Price = 461.718092748764m,
                            ReleaseDate = new DateTime(2022, 11, 18, 23, 20, 40, 812, DateTimeKind.Local).AddTicks(5622),
                            Title = "Gorgeous Frozen Towels"
                        },
                        new
                        {
                            Id = 17,
                            Barcode = "7",
                            Description = "Boston's most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles",
                            Price = 126.128098112125m,
                            ReleaseDate = new DateTime(2023, 6, 28, 13, 42, 12, 390, DateTimeKind.Local).AddTicks(5139),
                            Title = "Tasty Steel Cheese"
                        },
                        new
                        {
                            Id = 18,
                            Barcode = "8",
                            Description = "New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart",
                            Price = 530.970371435383m,
                            ReleaseDate = new DateTime(2023, 6, 25, 15, 24, 53, 749, DateTimeKind.Local).AddTicks(8224),
                            Title = "Gorgeous Granite Cheese"
                        },
                        new
                        {
                            Id = 19,
                            Barcode = "9",
                            Description = "The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive",
                            Price = 913.003066283186m,
                            ReleaseDate = new DateTime(2022, 11, 19, 2, 42, 53, 329, DateTimeKind.Local).AddTicks(1667),
                            Title = "Sleek Rubber Chicken"
                        },
                        new
                        {
                            Id = 20,
                            Barcode = "5",
                            Description = "Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals",
                            Price = 940.814879371698m,
                            ReleaseDate = new DateTime(2023, 4, 12, 4, 13, 37, 811, DateTimeKind.Local).AddTicks(4947),
                            Title = "Intelligent Wooden Salad"
                        },
                        new
                        {
                            Id = 21,
                            Barcode = "4",
                            Description = "Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support",
                            Price = 479.41424090062m,
                            ReleaseDate = new DateTime(2023, 6, 20, 15, 36, 31, 999, DateTimeKind.Local).AddTicks(7359),
                            Title = "Handcrafted Wooden Sausages"
                        },
                        new
                        {
                            Id = 22,
                            Barcode = "7",
                            Description = "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit",
                            Price = 320.499838554068m,
                            ReleaseDate = new DateTime(2023, 1, 31, 11, 3, 54, 269, DateTimeKind.Local).AddTicks(5114),
                            Title = "Sleek Granite Car"
                        },
                        new
                        {
                            Id = 23,
                            Barcode = "6",
                            Description = "The Nagasaki Lander is the trademarked name of several series of Nagasaki sport bikes, that started with the 1984 ABC800J",
                            Price = 478.915239043029m,
                            ReleaseDate = new DateTime(2023, 6, 2, 4, 54, 1, 587, DateTimeKind.Local).AddTicks(8712),
                            Title = "Small Wooden Car"
                        },
                        new
                        {
                            Id = 24,
                            Barcode = "2",
                            Description = "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients",
                            Price = 910.785444308438m,
                            ReleaseDate = new DateTime(2023, 7, 3, 21, 30, 20, 817, DateTimeKind.Local).AddTicks(1911),
                            Title = "Sleek Steel Shirt"
                        },
                        new
                        {
                            Id = 25,
                            Barcode = "3",
                            Description = "New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016",
                            Price = 802.238750720974m,
                            ReleaseDate = new DateTime(2023, 7, 19, 22, 59, 12, 380, DateTimeKind.Local).AddTicks(8394),
                            Title = "Incredible Frozen Mouse"
                        },
                        new
                        {
                            Id = 26,
                            Barcode = "7",
                            Description = "The Nagasaki Lander is the trademarked name of several series of Nagasaki sport bikes, that started with the 1984 ABC800J",
                            Price = 150.818741621831m,
                            ReleaseDate = new DateTime(2023, 5, 14, 16, 35, 32, 504, DateTimeKind.Local).AddTicks(3747),
                            Title = "Incredible Wooden Chair"
                        },
                        new
                        {
                            Id = 27,
                            Barcode = "5",
                            Description = "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit",
                            Price = 721.773541800572m,
                            ReleaseDate = new DateTime(2023, 2, 3, 4, 39, 8, 500, DateTimeKind.Local).AddTicks(5359),
                            Title = "Gorgeous Plastic Chips"
                        },
                        new
                        {
                            Id = 28,
                            Barcode = "5",
                            Description = "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit",
                            Price = 688.245783060904m,
                            ReleaseDate = new DateTime(2023, 4, 28, 7, 5, 3, 612, DateTimeKind.Local).AddTicks(611),
                            Title = "Incredible Fresh Bacon"
                        },
                        new
                        {
                            Id = 29,
                            Barcode = "7",
                            Description = "Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support",
                            Price = 553.558320945389m,
                            ReleaseDate = new DateTime(2023, 7, 21, 17, 35, 57, 605, DateTimeKind.Local).AddTicks(1948),
                            Title = "Incredible Soft Computer"
                        },
                        new
                        {
                            Id = 30,
                            Barcode = "4",
                            Description = "New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016",
                            Price = 663.536718269594m,
                            ReleaseDate = new DateTime(2022, 11, 15, 18, 31, 20, 821, DateTimeKind.Local).AddTicks(3768),
                            Title = "Handcrafted Rubber Bike"
                        },
                        new
                        {
                            Id = 31,
                            Barcode = "2",
                            Description = "Boston's most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles",
                            Price = 922.479030014704m,
                            ReleaseDate = new DateTime(2023, 10, 11, 16, 57, 10, 18, DateTimeKind.Local).AddTicks(1956),
                            Title = "Handcrafted Concrete Tuna"
                        },
                        new
                        {
                            Id = 32,
                            Barcode = "3",
                            Description = "The slim & simple Maple Gaming Keyboard from Dev Byte comes with a sleek body and 7- Color RGB LED Back-lighting for smart functionality",
                            Price = 255.49067058018m,
                            ReleaseDate = new DateTime(2023, 7, 22, 12, 44, 35, 957, DateTimeKind.Local).AddTicks(2421),
                            Title = "Gorgeous Wooden Fish"
                        },
                        new
                        {
                            Id = 33,
                            Barcode = "7",
                            Description = "New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016",
                            Price = 955.272407213818m,
                            ReleaseDate = new DateTime(2023, 4, 29, 13, 13, 37, 207, DateTimeKind.Local).AddTicks(8405),
                            Title = "Handcrafted Frozen Keyboard"
                        },
                        new
                        {
                            Id = 34,
                            Barcode = "8",
                            Description = "The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive",
                            Price = 151.982358236323m,
                            ReleaseDate = new DateTime(2022, 11, 26, 6, 29, 25, 46, DateTimeKind.Local).AddTicks(6040),
                            Title = "Intelligent Plastic Chair"
                        },
                        new
                        {
                            Id = 35,
                            Barcode = "9",
                            Description = "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit",
                            Price = 434.299358334532m,
                            ReleaseDate = new DateTime(2022, 12, 14, 11, 21, 43, 41, DateTimeKind.Local).AddTicks(5756),
                            Title = "Unbranded Wooden Pizza"
                        },
                        new
                        {
                            Id = 36,
                            Barcode = "4",
                            Description = "The Nagasaki Lander is the trademarked name of several series of Nagasaki sport bikes, that started with the 1984 ABC800J",
                            Price = 57.7988712865854m,
                            ReleaseDate = new DateTime(2023, 1, 3, 5, 55, 40, 574, DateTimeKind.Local).AddTicks(7582),
                            Title = "Gorgeous Rubber Bacon"
                        },
                        new
                        {
                            Id = 37,
                            Barcode = "7",
                            Description = "New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart",
                            Price = 883.980300599234m,
                            ReleaseDate = new DateTime(2023, 3, 31, 21, 28, 53, 970, DateTimeKind.Local).AddTicks(5780),
                            Title = "Handcrafted Rubber Shirt"
                        },
                        new
                        {
                            Id = 38,
                            Barcode = "7",
                            Description = "Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support",
                            Price = 822.452619476455m,
                            ReleaseDate = new DateTime(2023, 1, 10, 19, 30, 34, 289, DateTimeKind.Local).AddTicks(7193),
                            Title = "Rustic Granite Shoes"
                        },
                        new
                        {
                            Id = 39,
                            Barcode = "7",
                            Description = "The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design",
                            Price = 22.2432652671092m,
                            ReleaseDate = new DateTime(2023, 4, 7, 3, 8, 48, 849, DateTimeKind.Local).AddTicks(2513),
                            Title = "Sleek Granite Chair"
                        },
                        new
                        {
                            Id = 40,
                            Barcode = "2",
                            Description = "The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive",
                            Price = 158.364214679396m,
                            ReleaseDate = new DateTime(2023, 6, 24, 23, 55, 5, 473, DateTimeKind.Local).AddTicks(334),
                            Title = "Incredible Rubber Soap"
                        },
                        new
                        {
                            Id = 41,
                            Barcode = "7",
                            Description = "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit",
                            Price = 533.504530191656m,
                            ReleaseDate = new DateTime(2023, 8, 7, 7, 0, 27, 621, DateTimeKind.Local).AddTicks(2420),
                            Title = "Awesome Soft Fish"
                        },
                        new
                        {
                            Id = 42,
                            Barcode = "8",
                            Description = "The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive",
                            Price = 265.709933652407m,
                            ReleaseDate = new DateTime(2023, 7, 29, 18, 11, 27, 50, DateTimeKind.Local).AddTicks(7763),
                            Title = "Intelligent Cotton Tuna"
                        },
                        new
                        {
                            Id = 43,
                            Barcode = "2",
                            Description = "The Nagasaki Lander is the trademarked name of several series of Nagasaki sport bikes, that started with the 1984 ABC800J",
                            Price = 294.402654204239m,
                            ReleaseDate = new DateTime(2023, 1, 21, 9, 57, 40, 606, DateTimeKind.Local).AddTicks(7780),
                            Title = "Refined Soft Bike"
                        },
                        new
                        {
                            Id = 44,
                            Barcode = "5",
                            Description = "Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals",
                            Price = 741.648888164036m,
                            ReleaseDate = new DateTime(2023, 1, 25, 7, 38, 5, 765, DateTimeKind.Local).AddTicks(5662),
                            Title = "Handmade Cotton Bacon"
                        },
                        new
                        {
                            Id = 45,
                            Barcode = "5",
                            Description = "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit",
                            Price = 825.239833488706m,
                            ReleaseDate = new DateTime(2023, 1, 3, 3, 44, 28, 835, DateTimeKind.Local).AddTicks(7282),
                            Title = "Small Soft Tuna"
                        },
                        new
                        {
                            Id = 46,
                            Barcode = "1",
                            Description = "The slim & simple Maple Gaming Keyboard from Dev Byte comes with a sleek body and 7- Color RGB LED Back-lighting for smart functionality",
                            Price = 305.894089151124m,
                            ReleaseDate = new DateTime(2023, 5, 8, 8, 26, 40, 395, DateTimeKind.Local).AddTicks(1044),
                            Title = "Practical Frozen Computer"
                        },
                        new
                        {
                            Id = 47,
                            Barcode = "4",
                            Description = "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients",
                            Price = 778.911179241683m,
                            ReleaseDate = new DateTime(2023, 1, 11, 3, 26, 14, 697, DateTimeKind.Local).AddTicks(4280),
                            Title = "Rustic Wooden Mouse"
                        },
                        new
                        {
                            Id = 48,
                            Barcode = "2",
                            Description = "New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart",
                            Price = 318.709401070936m,
                            ReleaseDate = new DateTime(2023, 2, 23, 0, 18, 32, 123, DateTimeKind.Local).AddTicks(4401),
                            Title = "Handcrafted Metal Mouse"
                        },
                        new
                        {
                            Id = 49,
                            Barcode = "6",
                            Description = "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients",
                            Price = 463.195345650052m,
                            ReleaseDate = new DateTime(2023, 4, 8, 5, 0, 35, 725, DateTimeKind.Local).AddTicks(4043),
                            Title = "Handcrafted Rubber Salad"
                        },
                        new
                        {
                            Id = 50,
                            Barcode = "6",
                            Description = "Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support",
                            Price = 717.609017980569m,
                            ReleaseDate = new DateTime(2023, 8, 25, 18, 9, 34, 905, DateTimeKind.Local).AddTicks(2878),
                            Title = "Incredible Plastic Shoes"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
