// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using P05Shop.API.Models;

#nullable disable

namespace P05Shop.API.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20231106001815_migracja")]
    partial class migracja
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("P06Shop.Shared.Shop.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(5000)
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Pages")
                        .HasColumnType("int");

                    b.Property<DateTime>("ReleaseDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design",
                            Pages = 830,
                            ReleaseDate = new DateTime(2023, 5, 12, 11, 30, 23, 549, DateTimeKind.Local).AddTicks(5577),
                            Title = "Gorgeous Wooden Chair"
                        },
                        new
                        {
                            Id = 2,
                            Description = "New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart",
                            Pages = 96,
                            ReleaseDate = new DateTime(2023, 7, 1, 8, 32, 28, 513, DateTimeKind.Local).AddTicks(3824),
                            Title = "Intelligent Cotton Towels"
                        },
                        new
                        {
                            Id = 3,
                            Description = "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients",
                            Pages = 712,
                            ReleaseDate = new DateTime(2023, 3, 20, 6, 38, 15, 459, DateTimeKind.Local).AddTicks(690),
                            Title = "Generic Wooden Fish"
                        },
                        new
                        {
                            Id = 4,
                            Description = "The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive",
                            Pages = 675,
                            ReleaseDate = new DateTime(2022, 12, 20, 18, 22, 31, 505, DateTimeKind.Local).AddTicks(2933),
                            Title = "Handcrafted Steel Shoes"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support",
                            Pages = 699,
                            ReleaseDate = new DateTime(2023, 4, 17, 13, 46, 42, 575, DateTimeKind.Local).AddTicks(985),
                            Title = "Ergonomic Plastic Car"
                        },
                        new
                        {
                            Id = 6,
                            Description = "The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive",
                            Pages = 839,
                            ReleaseDate = new DateTime(2023, 9, 30, 3, 16, 49, 95, DateTimeKind.Local).AddTicks(2399),
                            Title = "Fantastic Rubber Salad"
                        },
                        new
                        {
                            Id = 7,
                            Description = "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit",
                            Pages = 176,
                            ReleaseDate = new DateTime(2023, 2, 10, 12, 51, 19, 918, DateTimeKind.Local).AddTicks(5102),
                            Title = "Handmade Granite Table"
                        },
                        new
                        {
                            Id = 8,
                            Description = "Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support",
                            Pages = 703,
                            ReleaseDate = new DateTime(2023, 5, 5, 9, 25, 6, 512, DateTimeKind.Local).AddTicks(7611),
                            Title = "Ergonomic Steel Pants"
                        },
                        new
                        {
                            Id = 9,
                            Description = "The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design",
                            Pages = 198,
                            ReleaseDate = new DateTime(2023, 1, 18, 22, 10, 32, 368, DateTimeKind.Local).AddTicks(4513),
                            Title = "Small Plastic Table"
                        },
                        new
                        {
                            Id = 10,
                            Description = "The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive",
                            Pages = 276,
                            ReleaseDate = new DateTime(2023, 5, 7, 0, 11, 6, 321, DateTimeKind.Local).AddTicks(7392),
                            Title = "Handmade Wooden Table"
                        },
                        new
                        {
                            Id = 11,
                            Description = "Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals",
                            Pages = 415,
                            ReleaseDate = new DateTime(2023, 5, 11, 4, 51, 18, 267, DateTimeKind.Local).AddTicks(6591),
                            Title = "Fantastic Concrete Chicken"
                        },
                        new
                        {
                            Id = 12,
                            Description = "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit",
                            Pages = 160,
                            ReleaseDate = new DateTime(2023, 8, 20, 10, 24, 2, 727, DateTimeKind.Local).AddTicks(6012),
                            Title = "Practical Granite Ball"
                        },
                        new
                        {
                            Id = 13,
                            Description = "Boston's most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles",
                            Pages = 74,
                            ReleaseDate = new DateTime(2023, 3, 22, 12, 21, 46, 683, DateTimeKind.Local).AddTicks(9438),
                            Title = "Intelligent Steel Salad"
                        },
                        new
                        {
                            Id = 14,
                            Description = "The Football Is Good For Training And Recreational Purposes",
                            Pages = 987,
                            ReleaseDate = new DateTime(2023, 6, 22, 2, 1, 19, 714, DateTimeKind.Local).AddTicks(4991),
                            Title = "Sleek Steel Tuna"
                        },
                        new
                        {
                            Id = 15,
                            Description = "The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive",
                            Pages = 360,
                            ReleaseDate = new DateTime(2023, 2, 20, 11, 42, 14, 457, DateTimeKind.Local).AddTicks(2309),
                            Title = "Ergonomic Steel Shirt"
                        },
                        new
                        {
                            Id = 16,
                            Description = "Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals",
                            Pages = 246,
                            ReleaseDate = new DateTime(2022, 11, 9, 16, 57, 1, 641, DateTimeKind.Local).AddTicks(9121),
                            Title = "Handcrafted Rubber Bike"
                        },
                        new
                        {
                            Id = 17,
                            Description = "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients",
                            Pages = 643,
                            ReleaseDate = new DateTime(2023, 8, 18, 2, 10, 6, 205, DateTimeKind.Local).AddTicks(3704),
                            Title = "Small Steel Tuna"
                        },
                        new
                        {
                            Id = 18,
                            Description = "New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016",
                            Pages = 181,
                            ReleaseDate = new DateTime(2023, 9, 3, 23, 29, 47, 566, DateTimeKind.Local).AddTicks(9783),
                            Title = "Gorgeous Cotton Keyboard"
                        },
                        new
                        {
                            Id = 19,
                            Description = "New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart",
                            Pages = 627,
                            ReleaseDate = new DateTime(2023, 8, 2, 21, 20, 47, 125, DateTimeKind.Local).AddTicks(9228),
                            Title = "Unbranded Steel Car"
                        },
                        new
                        {
                            Id = 20,
                            Description = "The slim & simple Maple Gaming Keyboard from Dev Byte comes with a sleek body and 7- Color RGB LED Back-lighting for smart functionality",
                            Pages = 887,
                            ReleaseDate = new DateTime(2023, 6, 7, 18, 59, 58, 807, DateTimeKind.Local).AddTicks(3152),
                            Title = "Refined Fresh Mouse"
                        },
                        new
                        {
                            Id = 21,
                            Description = "The Football Is Good For Training And Recreational Purposes",
                            Pages = 939,
                            ReleaseDate = new DateTime(2023, 4, 4, 22, 41, 59, 976, DateTimeKind.Local).AddTicks(9952),
                            Title = "Ergonomic Plastic Computer"
                        },
                        new
                        {
                            Id = 22,
                            Description = "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients",
                            Pages = 705,
                            ReleaseDate = new DateTime(2023, 11, 4, 17, 50, 20, 455, DateTimeKind.Local).AddTicks(128),
                            Title = "Tasty Plastic Cheese"
                        },
                        new
                        {
                            Id = 23,
                            Description = "The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design",
                            Pages = 331,
                            ReleaseDate = new DateTime(2023, 4, 10, 23, 50, 46, 399, DateTimeKind.Local).AddTicks(7274),
                            Title = "Tasty Metal Pants"
                        },
                        new
                        {
                            Id = 24,
                            Description = "New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016",
                            Pages = 224,
                            ReleaseDate = new DateTime(2023, 6, 28, 13, 56, 27, 665, DateTimeKind.Local).AddTicks(2291),
                            Title = "Intelligent Fresh Bacon"
                        },
                        new
                        {
                            Id = 25,
                            Description = "Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals",
                            Pages = 42,
                            ReleaseDate = new DateTime(2023, 6, 10, 7, 7, 36, 554, DateTimeKind.Local).AddTicks(9093),
                            Title = "Handcrafted Fresh Sausages"
                        },
                        new
                        {
                            Id = 26,
                            Description = "New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016",
                            Pages = 781,
                            ReleaseDate = new DateTime(2023, 7, 11, 11, 32, 20, 686, DateTimeKind.Local).AddTicks(1536),
                            Title = "Licensed Metal Mouse"
                        },
                        new
                        {
                            Id = 27,
                            Description = "The Football Is Good For Training And Recreational Purposes",
                            Pages = 249,
                            ReleaseDate = new DateTime(2022, 12, 18, 5, 55, 43, 121, DateTimeKind.Local).AddTicks(9950),
                            Title = "Ergonomic Metal Shoes"
                        },
                        new
                        {
                            Id = 28,
                            Description = "Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support",
                            Pages = 813,
                            ReleaseDate = new DateTime(2022, 11, 19, 16, 0, 58, 514, DateTimeKind.Local).AddTicks(3790),
                            Title = "Fantastic Frozen Gloves"
                        },
                        new
                        {
                            Id = 29,
                            Description = "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit",
                            Pages = 107,
                            ReleaseDate = new DateTime(2023, 10, 29, 22, 17, 30, 455, DateTimeKind.Local).AddTicks(1018),
                            Title = "Unbranded Granite Hat"
                        },
                        new
                        {
                            Id = 30,
                            Description = "New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart",
                            Pages = 906,
                            ReleaseDate = new DateTime(2023, 10, 9, 21, 37, 52, 583, DateTimeKind.Local).AddTicks(2721),
                            Title = "Generic Fresh Computer"
                        },
                        new
                        {
                            Id = 31,
                            Description = "The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design",
                            Pages = 125,
                            ReleaseDate = new DateTime(2022, 11, 13, 9, 24, 9, 321, DateTimeKind.Local).AddTicks(9406),
                            Title = "Generic Steel Ball"
                        },
                        new
                        {
                            Id = 32,
                            Description = "Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support",
                            Pages = 312,
                            ReleaseDate = new DateTime(2023, 3, 14, 23, 35, 31, 587, DateTimeKind.Local).AddTicks(5641),
                            Title = "Licensed Soft Salad"
                        },
                        new
                        {
                            Id = 33,
                            Description = "Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals",
                            Pages = 843,
                            ReleaseDate = new DateTime(2023, 8, 8, 14, 51, 56, 724, DateTimeKind.Local).AddTicks(9996),
                            Title = "Ergonomic Metal Soap"
                        },
                        new
                        {
                            Id = 34,
                            Description = "Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals",
                            Pages = 75,
                            ReleaseDate = new DateTime(2023, 4, 11, 0, 52, 59, 688, DateTimeKind.Local).AddTicks(5369),
                            Title = "Ergonomic Rubber Car"
                        },
                        new
                        {
                            Id = 35,
                            Description = "The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive",
                            Pages = 625,
                            ReleaseDate = new DateTime(2022, 11, 29, 17, 21, 22, 517, DateTimeKind.Local).AddTicks(8232),
                            Title = "Unbranded Wooden Soap"
                        },
                        new
                        {
                            Id = 36,
                            Description = "The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design",
                            Pages = 929,
                            ReleaseDate = new DateTime(2023, 8, 16, 19, 23, 53, 498, DateTimeKind.Local).AddTicks(8882),
                            Title = "Intelligent Plastic Cheese"
                        },
                        new
                        {
                            Id = 37,
                            Description = "The slim & simple Maple Gaming Keyboard from Dev Byte comes with a sleek body and 7- Color RGB LED Back-lighting for smart functionality",
                            Pages = 233,
                            ReleaseDate = new DateTime(2023, 10, 22, 16, 1, 30, 301, DateTimeKind.Local).AddTicks(646),
                            Title = "Generic Steel Pizza"
                        },
                        new
                        {
                            Id = 38,
                            Description = "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients",
                            Pages = 530,
                            ReleaseDate = new DateTime(2023, 5, 19, 2, 7, 13, 781, DateTimeKind.Local).AddTicks(451),
                            Title = "Ergonomic Fresh Keyboard"
                        },
                        new
                        {
                            Id = 39,
                            Description = "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients",
                            Pages = 707,
                            ReleaseDate = new DateTime(2023, 7, 17, 0, 37, 22, 418, DateTimeKind.Local).AddTicks(4984),
                            Title = "Fantastic Metal Chair"
                        },
                        new
                        {
                            Id = 40,
                            Description = "Boston's most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles",
                            Pages = 472,
                            ReleaseDate = new DateTime(2022, 11, 20, 16, 40, 27, 751, DateTimeKind.Local).AddTicks(1670),
                            Title = "Small Metal Sausages"
                        },
                        new
                        {
                            Id = 41,
                            Description = "Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals",
                            Pages = 826,
                            ReleaseDate = new DateTime(2022, 11, 12, 8, 5, 36, 270, DateTimeKind.Local).AddTicks(7967),
                            Title = "Fantastic Metal Keyboard"
                        },
                        new
                        {
                            Id = 42,
                            Description = "The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design",
                            Pages = 306,
                            ReleaseDate = new DateTime(2023, 1, 10, 13, 50, 0, 906, DateTimeKind.Local).AddTicks(1404),
                            Title = "Refined Metal Fish"
                        },
                        new
                        {
                            Id = 43,
                            Description = "Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support",
                            Pages = 902,
                            ReleaseDate = new DateTime(2023, 8, 11, 23, 20, 57, 763, DateTimeKind.Local).AddTicks(3602),
                            Title = "Fantastic Soft Pants"
                        },
                        new
                        {
                            Id = 44,
                            Description = "The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive",
                            Pages = 764,
                            ReleaseDate = new DateTime(2022, 11, 18, 16, 10, 22, 830, DateTimeKind.Local).AddTicks(9427),
                            Title = "Practical Steel Tuna"
                        },
                        new
                        {
                            Id = 45,
                            Description = "The Nagasaki Lander is the trademarked name of several series of Nagasaki sport bikes, that started with the 1984 ABC800J",
                            Pages = 378,
                            ReleaseDate = new DateTime(2023, 8, 1, 6, 55, 53, 935, DateTimeKind.Local).AddTicks(8668),
                            Title = "Unbranded Cotton Soap"
                        },
                        new
                        {
                            Id = 46,
                            Description = "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients",
                            Pages = 956,
                            ReleaseDate = new DateTime(2023, 4, 9, 23, 12, 43, 394, DateTimeKind.Local).AddTicks(204),
                            Title = "Gorgeous Frozen Towels"
                        },
                        new
                        {
                            Id = 47,
                            Description = "New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016",
                            Pages = 993,
                            ReleaseDate = new DateTime(2023, 1, 5, 23, 31, 47, 261, DateTimeKind.Local).AddTicks(202),
                            Title = "Unbranded Wooden Chair"
                        },
                        new
                        {
                            Id = 48,
                            Description = "New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016",
                            Pages = 462,
                            ReleaseDate = new DateTime(2022, 11, 18, 22, 50, 42, 402, DateTimeKind.Local).AddTicks(7805),
                            Title = "Handmade Steel Pants"
                        },
                        new
                        {
                            Id = 49,
                            Description = "Boston's most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles",
                            Pages = 267,
                            ReleaseDate = new DateTime(2023, 6, 1, 21, 9, 46, 592, DateTimeKind.Local).AddTicks(7410),
                            Title = "Tasty Steel Cheese"
                        },
                        new
                        {
                            Id = 50,
                            Description = "New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016",
                            Pages = 16,
                            ReleaseDate = new DateTime(2023, 5, 24, 22, 11, 33, 135, DateTimeKind.Local).AddTicks(9500),
                            Title = "Incredible Concrete Salad"
                        });
                });

            modelBuilder.Entity("P06Shop.Shared.Shop.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Barcode")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(8,2)");

                    b.Property<DateTime>("ReleaseDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Barcode = "3",
                            Description = "The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design",
                            Price = 712.021981759007m,
                            ReleaseDate = new DateTime(2023, 3, 20, 6, 38, 15, 452, DateTimeKind.Local).AddTicks(7271),
                            Title = "Gorgeous Wooden Chair"
                        },
                        new
                        {
                            Id = 2,
                            Barcode = "7",
                            Description = "The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive",
                            Price = 839.010165513032m,
                            ReleaseDate = new DateTime(2023, 9, 30, 3, 16, 49, 88, DateTimeKind.Local).AddTicks(9777),
                            Title = "Handcrafted Steel Shoes"
                        },
                        new
                        {
                            Id = 3,
                            Barcode = "1",
                            Description = "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit",
                            Price = 198.083692779804m,
                            ReleaseDate = new DateTime(2023, 1, 18, 22, 10, 32, 362, DateTimeKind.Local).AddTicks(1791),
                            Title = "Handmade Granite Table"
                        },
                        new
                        {
                            Id = 4,
                            Barcode = "1",
                            Description = "The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive",
                            Price = 160.643399712929m,
                            ReleaseDate = new DateTime(2023, 8, 20, 10, 24, 2, 721, DateTimeKind.Local).AddTicks(3171),
                            Title = "Handmade Wooden Table"
                        },
                        new
                        {
                            Id = 5,
                            Barcode = "0",
                            Description = "Boston's most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles",
                            Price = 359.887736376788m,
                            ReleaseDate = new DateTime(2023, 2, 20, 11, 42, 14, 450, DateTimeKind.Local).AddTicks(9353),
                            Title = "Intelligent Steel Salad"
                        },
                        new
                        {
                            Id = 6,
                            Barcode = "8",
                            Description = "Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals",
                            Price = 181.360829243139m,
                            ReleaseDate = new DateTime(2023, 9, 3, 23, 29, 47, 560, DateTimeKind.Local).AddTicks(6700),
                            Title = "Handcrafted Rubber Bike"
                        },
                        new
                        {
                            Id = 7,
                            Barcode = "1",
                            Description = "New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart",
                            Price = 938.297015022625m,
                            ReleaseDate = new DateTime(2023, 4, 4, 22, 41, 59, 970, DateTimeKind.Local).AddTicks(6754),
                            Title = "Unbranded Steel Car"
                        },
                        new
                        {
                            Id = 8,
                            Barcode = "3",
                            Description = "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients",
                            Price = 223.882037785315m,
                            ReleaseDate = new DateTime(2023, 6, 28, 13, 56, 27, 658, DateTimeKind.Local).AddTicks(8983),
                            Title = "Tasty Plastic Cheese"
                        },
                        new
                        {
                            Id = 9,
                            Barcode = "0",
                            Description = "Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals",
                            Price = 249.172251003875m,
                            ReleaseDate = new DateTime(2022, 12, 18, 5, 55, 43, 115, DateTimeKind.Local).AddTicks(6454),
                            Title = "Handcrafted Fresh Sausages"
                        },
                        new
                        {
                            Id = 10,
                            Barcode = "1",
                            Description = "Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support",
                            Price = 905.322284099796m,
                            ReleaseDate = new DateTime(2023, 10, 9, 21, 37, 52, 576, DateTimeKind.Local).AddTicks(9109),
                            Title = "Fantastic Frozen Gloves"
                        },
                        new
                        {
                            Id = 11,
                            Barcode = "3",
                            Description = "The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design",
                            Price = 842.480734222792m,
                            ReleaseDate = new DateTime(2023, 8, 8, 14, 51, 56, 718, DateTimeKind.Local).AddTicks(6272),
                            Title = "Generic Steel Ball"
                        },
                        new
                        {
                            Id = 12,
                            Barcode = "1",
                            Description = "Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals",
                            Price = 928.928430071533m,
                            ReleaseDate = new DateTime(2023, 8, 16, 19, 23, 53, 492, DateTimeKind.Local).AddTicks(4976),
                            Title = "Ergonomic Rubber Car"
                        },
                        new
                        {
                            Id = 13,
                            Barcode = "6",
                            Description = "The slim & simple Maple Gaming Keyboard from Dev Byte comes with a sleek body and 7- Color RGB LED Back-lighting for smart functionality",
                            Price = 706.948686653259m,
                            ReleaseDate = new DateTime(2023, 7, 17, 0, 37, 22, 412, DateTimeKind.Local).AddTicks(995),
                            Title = "Generic Steel Pizza"
                        },
                        new
                        {
                            Id = 14,
                            Barcode = "3",
                            Description = "Boston's most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles",
                            Price = 306.262494314584m,
                            ReleaseDate = new DateTime(2023, 1, 10, 13, 50, 0, 899, DateTimeKind.Local).AddTicks(7306),
                            Title = "Small Metal Sausages"
                        },
                        new
                        {
                            Id = 15,
                            Barcode = "2",
                            Description = "Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support",
                            Price = 378.222576259273m,
                            ReleaseDate = new DateTime(2023, 8, 1, 6, 55, 53, 929, DateTimeKind.Local).AddTicks(4454),
                            Title = "Fantastic Soft Pants"
                        },
                        new
                        {
                            Id = 16,
                            Barcode = "6",
                            Description = "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients",
                            Price = 461.718092748764m,
                            ReleaseDate = new DateTime(2022, 11, 18, 22, 50, 42, 396, DateTimeKind.Local).AddTicks(3307),
                            Title = "Gorgeous Frozen Towels"
                        },
                        new
                        {
                            Id = 17,
                            Barcode = "7",
                            Description = "Boston's most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles",
                            Price = 126.128098112125m,
                            ReleaseDate = new DateTime(2023, 6, 28, 13, 12, 13, 974, DateTimeKind.Local).AddTicks(2792),
                            Title = "Tasty Steel Cheese"
                        },
                        new
                        {
                            Id = 18,
                            Barcode = "8",
                            Description = "New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart",
                            Price = 530.970371435383m,
                            ReleaseDate = new DateTime(2023, 6, 25, 14, 54, 55, 333, DateTimeKind.Local).AddTicks(5843),
                            Title = "Gorgeous Granite Cheese"
                        },
                        new
                        {
                            Id = 19,
                            Barcode = "9",
                            Description = "The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive",
                            Price = 913.003066283186m,
                            ReleaseDate = new DateTime(2022, 11, 19, 2, 12, 54, 912, DateTimeKind.Local).AddTicks(9191),
                            Title = "Sleek Rubber Chicken"
                        },
                        new
                        {
                            Id = 20,
                            Barcode = "5",
                            Description = "Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals",
                            Price = 940.814879371698m,
                            ReleaseDate = new DateTime(2023, 4, 12, 3, 43, 39, 395, DateTimeKind.Local).AddTicks(2474),
                            Title = "Intelligent Wooden Salad"
                        },
                        new
                        {
                            Id = 21,
                            Barcode = "4",
                            Description = "Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support",
                            Price = 479.41424090062m,
                            ReleaseDate = new DateTime(2023, 6, 20, 15, 6, 33, 583, DateTimeKind.Local).AddTicks(4852),
                            Title = "Handcrafted Wooden Sausages"
                        },
                        new
                        {
                            Id = 22,
                            Barcode = "7",
                            Description = "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit",
                            Price = 320.499838554068m,
                            ReleaseDate = new DateTime(2023, 1, 31, 10, 33, 55, 853, DateTimeKind.Local).AddTicks(2570),
                            Title = "Sleek Granite Car"
                        },
                        new
                        {
                            Id = 23,
                            Barcode = "6",
                            Description = "The Nagasaki Lander is the trademarked name of several series of Nagasaki sport bikes, that started with the 1984 ABC800J",
                            Price = 478.915239043029m,
                            ReleaseDate = new DateTime(2023, 6, 2, 4, 24, 3, 171, DateTimeKind.Local).AddTicks(6134),
                            Title = "Small Wooden Car"
                        },
                        new
                        {
                            Id = 24,
                            Barcode = "2",
                            Description = "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients",
                            Price = 910.785444308438m,
                            ReleaseDate = new DateTime(2023, 7, 3, 21, 0, 22, 400, DateTimeKind.Local).AddTicks(9303),
                            Title = "Sleek Steel Shirt"
                        },
                        new
                        {
                            Id = 25,
                            Barcode = "3",
                            Description = "New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016",
                            Price = 802.238750720974m,
                            ReleaseDate = new DateTime(2023, 7, 19, 22, 29, 13, 964, DateTimeKind.Local).AddTicks(5752),
                            Title = "Incredible Frozen Mouse"
                        },
                        new
                        {
                            Id = 26,
                            Barcode = "7",
                            Description = "The Nagasaki Lander is the trademarked name of several series of Nagasaki sport bikes, that started with the 1984 ABC800J",
                            Price = 150.818741621831m,
                            ReleaseDate = new DateTime(2023, 5, 14, 16, 5, 34, 88, DateTimeKind.Local).AddTicks(1060),
                            Title = "Incredible Wooden Chair"
                        },
                        new
                        {
                            Id = 27,
                            Barcode = "5",
                            Description = "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit",
                            Price = 721.773541800572m,
                            ReleaseDate = new DateTime(2023, 2, 3, 4, 9, 10, 84, DateTimeKind.Local).AddTicks(2634),
                            Title = "Gorgeous Plastic Chips"
                        },
                        new
                        {
                            Id = 28,
                            Barcode = "5",
                            Description = "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit",
                            Price = 688.245783060904m,
                            ReleaseDate = new DateTime(2023, 4, 28, 6, 35, 5, 195, DateTimeKind.Local).AddTicks(7856),
                            Title = "Incredible Fresh Bacon"
                        },
                        new
                        {
                            Id = 29,
                            Barcode = "7",
                            Description = "Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support",
                            Price = 553.558320945389m,
                            ReleaseDate = new DateTime(2023, 7, 21, 17, 5, 59, 188, DateTimeKind.Local).AddTicks(9163),
                            Title = "Incredible Soft Computer"
                        },
                        new
                        {
                            Id = 30,
                            Barcode = "4",
                            Description = "New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016",
                            Price = 663.536718269594m,
                            ReleaseDate = new DateTime(2022, 11, 15, 18, 1, 22, 405, DateTimeKind.Local).AddTicks(950),
                            Title = "Handcrafted Rubber Bike"
                        },
                        new
                        {
                            Id = 31,
                            Barcode = "2",
                            Description = "Boston's most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles",
                            Price = 922.479030014704m,
                            ReleaseDate = new DateTime(2023, 10, 11, 16, 27, 11, 601, DateTimeKind.Local).AddTicks(9106),
                            Title = "Handcrafted Concrete Tuna"
                        },
                        new
                        {
                            Id = 32,
                            Barcode = "3",
                            Description = "The slim & simple Maple Gaming Keyboard from Dev Byte comes with a sleek body and 7- Color RGB LED Back-lighting for smart functionality",
                            Price = 255.49067058018m,
                            ReleaseDate = new DateTime(2023, 7, 22, 12, 14, 37, 540, DateTimeKind.Local).AddTicks(9539),
                            Title = "Gorgeous Wooden Fish"
                        },
                        new
                        {
                            Id = 33,
                            Barcode = "7",
                            Description = "New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016",
                            Price = 955.272407213818m,
                            ReleaseDate = new DateTime(2023, 4, 29, 12, 43, 38, 791, DateTimeKind.Local).AddTicks(5467),
                            Title = "Handcrafted Frozen Keyboard"
                        },
                        new
                        {
                            Id = 34,
                            Barcode = "8",
                            Description = "The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive",
                            Price = 151.982358236323m,
                            ReleaseDate = new DateTime(2022, 11, 26, 5, 59, 26, 630, DateTimeKind.Local).AddTicks(3070),
                            Title = "Intelligent Plastic Chair"
                        },
                        new
                        {
                            Id = 35,
                            Barcode = "9",
                            Description = "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit",
                            Price = 434.299358334532m,
                            ReleaseDate = new DateTime(2022, 12, 14, 10, 51, 44, 625, DateTimeKind.Local).AddTicks(2747),
                            Title = "Unbranded Wooden Pizza"
                        },
                        new
                        {
                            Id = 36,
                            Barcode = "4",
                            Description = "The Nagasaki Lander is the trademarked name of several series of Nagasaki sport bikes, that started with the 1984 ABC800J",
                            Price = 57.7988712865854m,
                            ReleaseDate = new DateTime(2023, 1, 3, 5, 25, 42, 158, DateTimeKind.Local).AddTicks(4544),
                            Title = "Gorgeous Rubber Bacon"
                        },
                        new
                        {
                            Id = 37,
                            Barcode = "7",
                            Description = "New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart",
                            Price = 883.980300599234m,
                            ReleaseDate = new DateTime(2023, 3, 31, 20, 58, 55, 554, DateTimeKind.Local).AddTicks(2705),
                            Title = "Handcrafted Rubber Shirt"
                        },
                        new
                        {
                            Id = 38,
                            Barcode = "7",
                            Description = "Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support",
                            Price = 822.452619476455m,
                            ReleaseDate = new DateTime(2023, 1, 10, 19, 0, 35, 873, DateTimeKind.Local).AddTicks(4080),
                            Title = "Rustic Granite Shoes"
                        },
                        new
                        {
                            Id = 39,
                            Barcode = "7",
                            Description = "The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design",
                            Price = 22.2432652671092m,
                            ReleaseDate = new DateTime(2023, 4, 7, 2, 38, 50, 432, DateTimeKind.Local).AddTicks(9229),
                            Title = "Sleek Granite Chair"
                        },
                        new
                        {
                            Id = 40,
                            Barcode = "2",
                            Description = "The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive",
                            Price = 158.364214679396m,
                            ReleaseDate = new DateTime(2023, 6, 24, 23, 25, 7, 56, DateTimeKind.Local).AddTicks(7101),
                            Title = "Incredible Rubber Soap"
                        },
                        new
                        {
                            Id = 41,
                            Barcode = "7",
                            Description = "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit",
                            Price = 533.504530191656m,
                            ReleaseDate = new DateTime(2023, 8, 7, 6, 30, 29, 204, DateTimeKind.Local).AddTicks(9155),
                            Title = "Awesome Soft Fish"
                        },
                        new
                        {
                            Id = 42,
                            Barcode = "8",
                            Description = "The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive",
                            Price = 265.709933652407m,
                            ReleaseDate = new DateTime(2023, 7, 29, 17, 41, 28, 634, DateTimeKind.Local).AddTicks(4468),
                            Title = "Intelligent Cotton Tuna"
                        },
                        new
                        {
                            Id = 43,
                            Barcode = "2",
                            Description = "The Nagasaki Lander is the trademarked name of several series of Nagasaki sport bikes, that started with the 1984 ABC800J",
                            Price = 294.402654204239m,
                            ReleaseDate = new DateTime(2023, 1, 21, 9, 27, 42, 190, DateTimeKind.Local).AddTicks(3447),
                            Title = "Refined Soft Bike"
                        },
                        new
                        {
                            Id = 44,
                            Barcode = "5",
                            Description = "Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals",
                            Price = 741.648888164036m,
                            ReleaseDate = new DateTime(2023, 1, 25, 7, 8, 7, 349, DateTimeKind.Local).AddTicks(1077),
                            Title = "Handmade Cotton Bacon"
                        },
                        new
                        {
                            Id = 45,
                            Barcode = "5",
                            Description = "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit",
                            Price = 825.239833488706m,
                            ReleaseDate = new DateTime(2023, 1, 3, 3, 14, 30, 419, DateTimeKind.Local).AddTicks(2598),
                            Title = "Small Soft Tuna"
                        },
                        new
                        {
                            Id = 46,
                            Barcode = "1",
                            Description = "The slim & simple Maple Gaming Keyboard from Dev Byte comes with a sleek body and 7- Color RGB LED Back-lighting for smart functionality",
                            Price = 305.894089151124m,
                            ReleaseDate = new DateTime(2023, 5, 8, 7, 56, 41, 978, DateTimeKind.Local).AddTicks(6109),
                            Title = "Practical Frozen Computer"
                        },
                        new
                        {
                            Id = 47,
                            Barcode = "4",
                            Description = "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients",
                            Price = 778.911179241683m,
                            ReleaseDate = new DateTime(2023, 1, 11, 2, 56, 16, 280, DateTimeKind.Local).AddTicks(9295),
                            Title = "Rustic Wooden Mouse"
                        },
                        new
                        {
                            Id = 48,
                            Barcode = "2",
                            Description = "New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart",
                            Price = 318.709401070936m,
                            ReleaseDate = new DateTime(2023, 2, 22, 23, 48, 33, 706, DateTimeKind.Local).AddTicks(8934),
                            Title = "Handcrafted Metal Mouse"
                        },
                        new
                        {
                            Id = 49,
                            Barcode = "6",
                            Description = "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients",
                            Price = 463.195345650052m,
                            ReleaseDate = new DateTime(2023, 4, 8, 4, 30, 37, 308, DateTimeKind.Local).AddTicks(8144),
                            Title = "Handcrafted Rubber Salad"
                        },
                        new
                        {
                            Id = 50,
                            Barcode = "6",
                            Description = "Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support",
                            Price = 717.609017980569m,
                            ReleaseDate = new DateTime(2023, 8, 25, 17, 39, 36, 488, DateTimeKind.Local).AddTicks(6825),
                            Title = "Incredible Plastic Shoes"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
