name: CI/CD with Selenium and Azure DevOps

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest

    services:
      mysql:
        image: mysql:latest
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: testdatabase
          MYSQL_USER: root
          MYSQL_PASSWORD: root
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
        
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.x
        
    - name: Restore dependencies
      run: dotnet workload restore
      
    - name: Build
      run: dotnet build --configuration Release

    - name: Set up MySQL
      run: |
        sudo /etc/init.d/mysql start
        mysql -e 'CREATE DATABASE ${{ env.DB_DATABASE }};' -u${{ env.DB_USER }} -p${{ env.DB_PASSWORD }}
      
    - name: Add Migration
      run: |
          cd .\P05Shop.API\
          dotnet tool install --global dotnet-ef
          dotnet tool update --global dotnet-ef
          dotnet ef migrations add 20231106004814_ReleaseDateRequired
          dotnet ef database update
          cd ..

    - name: Publish
      run: dotnet publish -c Release -o Files\dotnet/app
      
    - name: Run app
      run: | 
          cd .\P05Shop.API\
          cmd /c "start dotnet run --urls=https://localhost:7230;"
          ping 127.0.0.1 -n 10
          netstat -a
          cd ..
          dotnet test
          exit 1
          
    - name: Report error
      if: failure()
      run: |
        echo "xpp"
