name: CI/CD with Selenium and Azure DevOps

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Setup dataBase
      uses: shogo82148/actions-setup-mysql@v1.28.1
      with:
        mysql-version: "8.0"
        root-password: root
        password: root

    - name: Create database
      run: mysql -u root -proot -e "CREATE DATABASE IF NOT EXISTS testdatabase; USE testdatabase; CREATE TABLE books (Id INT PRIMARY KEY AUTO_INCREMENT, Description TEXT NOT NULL, Pages INT, ReleaseDate DATETIME, Title VARCHAR(100) NOT NULL); CREATE TABLE Products (Id INT PRIMARY KEY AUTO_INCREMENT, Barcode VARCHAR(12) NOT NULL, Description TEXT NOT NULL, Price DECIMAL(8,2), ReleaseDate DATETIME, Title VARCHAR(100) NOT NULL);"
            
    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.x
        root-password: root
        password: root
        
    - name: Restore dependencies
      run: dotnet workload restore
      
    - name: Build
      run: dotnet build --configuration Release
      
    - name: Add Migration
      run: |
          cd .\P05Shop.API\
          dotnet tool install --global dotnet-ef
          dotnet ef migrations add 20231106004814_ReleaseDateRequired
          dotnet ef database update
          cd ..

    - name: Publish
      run: dotnet publish -c Release -o Files\dotnet/app
      
    - name: Run app
      run: | 
          cd .\P05Shop.API\
          cmd /c "start dotnet run --urls=https://localhost:7230;"
          ping 127.0.0.1 -n 10 > nul
          cd ..
          dotnet test
          exit 1
          
    - name: Report error
      if: failure()
      run: |
        echo "xpp"
